"""add_unique_active_booking_index

Revision ID: bc7a77535329
Revises: a9e837d2f79e
Create Date: 2026-08-17 00:08:01.639178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7a77535329'
down_revision: Union[str, Sequence[str], None] = 'a9e837d2f79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_booking_per_seat', 'booking', ['showtime_id', 'seat_id'], unique=True, postgresql_where=sa.text("status = 'CONFIRMED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_booking_per_seat', table_name='booking', postgresql_where=sa.text("status = 'CONFIRMED'"))
    # ### end Alembic commands ###
